/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        primary: '#0D4A36',
        primaryText: '#0D6B47',
        primarySoft: '#E6F2EC',
        background: '#F4F8F6',
        surface: '#FFFFFF',
        border: '#DDE5E1',
        borderMid: '#C9D4CF',
        borderStrong: '#B9C7C1',
        text: '#14201B',
        muted: '#3B4A44',
        placeholder: '#5B6B64',
        amber: '#F5B301',
        accent: '#3DDC97',
        accentDeep: '#1FA971',
        successBg: '#DDEFE6',
        successFg: '#0B4A32',
        warnBg: '#FFE9A8',
        warnFg: '#5C4400',
        dangerBg: '#FBE0DD',
        dangerFg: '#8C1D18',
        tipBg: '#FFF4D1',
        neutralBg: '#E6EBE8',
        navInactive: '#4A5A53',
        alert: '#B3261E',
        success: '#0E7A4E',
        dangerSurface: '#FAF5F3',
        divider: '#E8EEEB',
      },
      fontFamily: {
        body: ['DMSans_400Regular'],
        'body-medium': ['DMSans_500Medium'],
        'body-semibold': ['DMSans_600SemiBold'],
        'body-bold': ['DMSans_700Bold'],
        heading: ['Sora_700Bold'],
        'heading-semibold': ['Sora_600SemiBold'],
      },
      borderRadius: {
        card: '22px',
        button: '18px',
        input: '16px',
        chip: '999px',
      },
    },
  },
  plugins: [],
};
